//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPage.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyPage.UI.Resources.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sou estudante de Análise e Desenvolvimento de Sistemas e trabalho com desenvolvimento de software há {0} anos e {1} meses, majoritariamente com foco em Backend na linguagem.
        /// </summary>
        public static string AboutBody_01 {
            get {
                return ResourceManager.GetString("AboutBody_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atuei em projetos nos quais também utilizei outras tecnologias, como frontend web (dashboard admin) em.
        /// </summary>
        public static string AboutBody_02 {
            get {
                return ResourceManager.GetString("AboutBody_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a , banco de dados em.
        /// </summary>
        public static string AboutBody_02_1 {
            get {
                return ResourceManager.GetString("AboutBody_02.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pessoalmente, abordo outros tópicos e tecnologias durante meus estudos, como desenvolvimento de aplicativos com React Native e plataformas de computação em nuvem, mais especificamente a Microsoft Azure, da qual obtive aprovação nas certificações AZ-900 e AZ-204..
        /// </summary>
        public static string AboutBody_03 {
            get {
                return ResourceManager.GetString("AboutBody_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a saber mais.
        /// </summary>
        public static string AboutButton {
            get {
                return ResourceManager.GetString("AboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C# .NET (.NET Core e .NET Framework)..
        /// </summary>
        public static string AboutEmphases_01 {
            get {
                return ResourceManager.GetString("AboutEmphases_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SQL Server, MySql, Redis e MongoDB, testes unitários e arquitetura em microsserviços..
        /// </summary>
        public static string AboutEmphases_02 {
            get {
                return ResourceManager.GetString("AboutEmphases_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a sobre.
        /// </summary>
        public static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SOBRE.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Olá, me chamo.
        /// </summary>
        public static string AboutTitle_Greeting {
            get {
                return ResourceManager.GetString("AboutTitle_Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Matheus de Assis.
        /// </summary>
        public static string AboutTitle_Name {
            get {
                return ResourceManager.GetString("AboutTitle_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atribuições.
        /// </summary>
        public static string Attributions {
            get {
                return ResourceManager.GetString("Attributions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a EXPERIÊNCIA.
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a veja mais detalhes no Linkedin.
        /// </summary>
        public static string BackgroundMore {
            get {
                return ResourceManager.GetString("BackgroundMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CERTIFICAÇÕES.
        /// </summary>
        public static string CertificationsTitle {
            get {
                return ResourceManager.GetString("CertificationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Empresa.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alocado na empresa.
        /// </summary>
        public static string CompanySubTitle {
            get {
                return ResourceManager.GetString("CompanySubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CONTATO.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a copiado!.
        /// </summary>
        public static string Copied {
            get {
                return ResourceManager.GetString("Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a cursos.
        /// </summary>
        public static string CoursesMenu {
            get {
                return ResourceManager.GetString("CoursesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a veja todos os meus certificados.
        /// </summary>
        public static string CoursesMore {
            get {
                return ResourceManager.GetString("CoursesMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CURSOS CONCLUÍDOS.
        /// </summary>
        public static string CoursesTitle {
            get {
                return ResourceManager.GetString("CoursesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a contato@matheusassis.dev.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;li&gt;Testes manuais em APIs, Workers e UI Admin;&lt;/li&gt;
        ///&lt;li&gt;Documentação de testes e detalhamento de fluxos do software;&lt;/li&gt;
        ///&lt;li&gt;Colaboração com a equipe de desenvolvimento, fornecendo feedback sobre a qualidade do software;&lt;/li&gt;.
        /// </summary>
        public static string FitbankAttri_01 {
            get {
                return ResourceManager.GetString("FitbankAttri_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;li&gt;Desenvolvimento de novas funcionalidades em projetos diversos;&lt;/li&gt;
        ///&lt;li&gt;Correção de bugs e implementações pontuais;&lt;/li&gt;
        ///&lt;li&gt;Elaboração de documentação para orientação e para novas entregas;&lt;/li&gt;
        ///&lt;li&gt;Revisões de código (code reviews), oferecendo feedback construtivo aos colegas de equipe;&lt;/li&gt;
        ///&lt;li&gt;Manutenção de APIs e Workers para integração de sistemas e serviços;&lt;/li&gt;.
        /// </summary>
        public static string FitbankAttri_02 {
            get {
                return ResourceManager.GetString("FitbankAttri_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a abr 2021.
        /// </summary>
        public static string FitbankDate_01 {
            get {
                return ResourceManager.GetString("FitbankDate_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a nov 2020.
        /// </summary>
        public static string FitbankDate_01_1 {
            get {
                return ResourceManager.GetString("FitbankDate_01.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ago 2021.
        /// </summary>
        public static string FitbankDate_02 {
            get {
                return ResourceManager.GetString("FitbankDate_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a abr 2021.
        /// </summary>
        public static string FitbankDate_02_1 {
            get {
                return ResourceManager.GetString("FitbankDate_02.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Testes manuais, Postman e SQL Server..
        /// </summary>
        public static string FitbankResume_01 {
            get {
                return ResourceManager.GetString("FitbankResume_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Backend com C# .NET Framework e frontend com C# ASP.NET MVC..
        /// </summary>
        public static string FitbankResume_02 {
            get {
                return ResourceManager.GetString("FitbankResume_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C#, .NET Framework, ASP.NET, Xamarin, JavaScript, SQL Server, APIs e Workers..
        /// </summary>
        public static string FitbankTechs_02 {
            get {
                return ResourceManager.GetString("FitbankTechs_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estagiário de Testes.
        /// </summary>
        public static string FitbankTitle_01 {
            get {
                return ResourceManager.GetString("FitbankTitle_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desenvolvedor Backend Junior.
        /// </summary>
        public static string FitbankTitle_02 {
            get {
                return ResourceManager.GetString("FitbankTitle_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esta é uma representação meramente ilustrativa de uma autoavaliação das minhas habilidades técnicas..
        /// </summary>
        public static string HardSkillsObs {
            get {
                return ResourceManager.GetString("HardSkillsObs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a horas.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Testes Integrados.
        /// </summary>
        public static string IntegrationTest {
            get {
                return ResourceManager.GetString("IntegrationTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;li&gt;Desenvolvimento de novas funcionalidades em projetos diversos;&lt;/li&gt;
        ///&lt;li&gt;Investigação e diagnóstico de erros em ambiente de produção;&lt;/li&gt;
        ///&lt;li&gt;Correção de bugs e implementações pontuais;&lt;/li&gt;
        ///&lt;li&gt;Criação e acompanhamento de processos de mudança (GMUD) em ambiente de produção;&lt;/li&gt;
        ///&lt;li&gt;Elaboração de documentação para orientação e para novas entregas;&lt;/li&gt;
        ///&lt;li&gt;Atuação em equipes de sustentação em projetos diversos;&lt;/li&gt;
        ///&lt;li&gt;Revisões de código (code reviews), oferecendo feedback construtivo aos colega [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string LabsitAttri_01 {
            get {
                return ResourceManager.GetString("LabsitAttri_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ago 2021.
        /// </summary>
        public static string LabsitDate_01 {
            get {
                return ResourceManager.GetString("LabsitDate_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a atualmente.
        /// </summary>
        public static string LabsitDate_01_1 {
            get {
                return ResourceManager.GetString("LabsitDate_01.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Backend com C# .NET e frontend com Angular (UI Admin&apos;s)..
        /// </summary>
        public static string LabsitResume_01 {
            get {
                return ResourceManager.GetString("LabsitResume_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C#, .NET Core, Angular, ASP.NET, .NET Framework, MySQL, SQL Server, Redis, APIs Rest, Microsserviços e Testes Unitários..
        /// </summary>
        public static string LabsitTechs_01 {
            get {
                return ResourceManager.GetString("LabsitTechs_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desenvolvedor Fullstack Pleno.
        /// </summary>
        public static string LabsitTitle_01 {
            get {
                return ResourceManager.GetString("LabsitTitle_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desenvolvedor Backend .NET.
        /// </summary>
        public static string MainStackBody {
            get {
                return ResourceManager.GetString("MainStackBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a STACK PRINCIPAL.
        /// </summary>
        public static string MainStackTitle {
            get {
                return ResourceManager.GetString("MainStackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a veja meus outros artigos.
        /// </summary>
        public static string MediumMore {
            get {
                return ResourceManager.GetString("MediumMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Publicado em.
        /// </summary>
        public static string MediumPostDate {
            get {
                return ResourceManager.GetString("MediumPostDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ARTIGOS NO MEDIUM.
        /// </summary>
        public static string MediumTitle {
            get {
                return ResourceManager.GetString("MediumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esta é minha página profissional, onde busco contar um resumo da minha trajetória, elencar conhecimentos e expor projetos pessoais..
        /// </summary>
        public static string PresentationText {
            get {
                return ResourceManager.GetString("PresentationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ver projetos.
        /// </summary>
        public static string ProjectsButton {
            get {
                return ResourceManager.GetString("ProjectsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a projetos.
        /// </summary>
        public static string ProjectsMenu {
            get {
                return ResourceManager.GetString("ProjectsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a pesquise um projeto.
        /// </summary>
        public static string SearchDefaultText {
            get {
                return ResourceManager.GetString("SearchDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a confira meus projetos pessoais.
        /// </summary>
        public static string SecondProjectsButton {
            get {
                return ResourceManager.GetString("SecondProjectsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ver menos.
        /// </summary>
        public static string SeeLess {
            get {
                return ResourceManager.GetString("SeeLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ver mais.
        /// </summary>
        public static string SeeMore {
            get {
                return ResourceManager.GetString("SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a HARD SKILLS.
        /// </summary>
        public static string SkillsTitle {
            get {
                return ResourceManager.GetString("SkillsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tecnologias.
        /// </summary>
        public static string Technologies {
            get {
                return ResourceManager.GetString("Technologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Testes Unitários.
        /// </summary>
        public static string UnitTest {
            get {
                return ResourceManager.GetString("UnitTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a vídeo.
        /// </summary>
        public static string VideoText {
            get {
                return ResourceManager.GetString("VideoText", resourceCulture);
            }
        }
    }
}
