//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPage.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResource_en_US2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource_en_US2() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyPage.UI.Resources.LanguageResource.en-US2", typeof(LanguageResource_en_US2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sou estudante de Análise e Desenvolvimento de Sistemas e trabalho com desenvolvimento de software há mais de dois anos, majoritariamente com foco em Backend na linguagem.
        /// </summary>
        public static string AboutBody_01 {
            get {
                return ResourceManager.GetString("AboutBody_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atuei em projetos nos quais também utilizei outras tecnologias, como frontend web (dashboard admin) em.
        /// </summary>
        public static string AboutBody_02 {
            get {
                return ResourceManager.GetString("AboutBody_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a , banco de dados em.
        /// </summary>
        public static string AboutBody_02_1 {
            get {
                return ResourceManager.GetString("AboutBody_02.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pessoalmente, abordo outros tópicos e tecnologias durante meus estudos, como desenvolvimento de aplicativos com React Native e plataformas de computação em nuvem, mais especificamente a Microsoft Azure, da qual obtive aprovação nas certificações AZ-900 e AZ-204..
        /// </summary>
        public static string AboutBody_03 {
            get {
                return ResourceManager.GetString("AboutBody_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a read more.
        /// </summary>
        public static string AboutButton {
            get {
                return ResourceManager.GetString("AboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C# .NET (.NET Core and .NET Framework)..
        /// </summary>
        public static string AboutEmphases_01 {
            get {
                return ResourceManager.GetString("AboutEmphases_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SQL Server, MySql, Redis e MongoDB, testes unitários e arquitetura em microsserviços..
        /// </summary>
        public static string AboutEmphases_02 {
            get {
                return ResourceManager.GetString("AboutEmphases_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hello, my name is.
        /// </summary>
        public static string AboutTitle_Greeting {
            get {
                return ResourceManager.GetString("AboutTitle_Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Matheus de Assis.
        /// </summary>
        public static string AboutTitle_Name {
            get {
                return ResourceManager.GetString("AboutTitle_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a BACKGROUND.
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CONTACT.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a november 2020 - april 2021.
        /// </summary>
        public static string Company01Date_01 {
            get {
                return ResourceManager.GetString("Company01Date_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a april 2021 - august 2021.
        /// </summary>
        public static string Company01Date_02 {
            get {
                return ResourceManager.GetString("Company01Date_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Testes manuais (exploratórios, em APIs e etc) e documentações de testes.
        /// </summary>
        public static string Company01Subtitle_01 {
            get {
                return ResourceManager.GetString("Company01Subtitle_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C#, .NET Framework, ASP.NET, Xamarin, JavaScript, SQL Server e APIs.
        /// </summary>
        public static string Company01Subtitle_02 {
            get {
                return ResourceManager.GetString("Company01Subtitle_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a QA Intern.
        /// </summary>
        public static string Company01Title_01 {
            get {
                return ResourceManager.GetString("Company01Title_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Junior Backend Developer.
        /// </summary>
        public static string Company01Title_02 {
            get {
                return ResourceManager.GetString("Company01Title_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a august 2021 - may 2022.
        /// </summary>
        public static string Company02Date_01 {
            get {
                return ResourceManager.GetString("Company02Date_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a january 2023 - today.
        /// </summary>
        public static string Company02Date_02 {
            get {
                return ResourceManager.GetString("Company02Date_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C#, .NET Core, MySQL, SQL Server, Redis, APIs Rest, Microsserviços e Testes Unitários.
        /// </summary>
        public static string Company02SubTitle_01 {
            get {
                return ResourceManager.GetString("Company02SubTitle_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C#, .NET Core, Angular 8, ASP.NET, .NET Framework, MySQL, SQL Server, APIs Rest, Microsserviços e Testes Unitários.
        /// </summary>
        public static string Company02SubTitle_02 {
            get {
                return ResourceManager.GetString("Company02SubTitle_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mid-level Backend Developer.
        /// </summary>
        public static string Company02Title_01 {
            get {
                return ResourceManager.GetString("Company02Title_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fullstack Developer.
        /// </summary>
        public static string Company02Title_02 {
            get {
                return ResourceManager.GetString("Company02Title_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .NET Backend Developer.
        /// </summary>
        public static string MainStackBody {
            get {
                return ResourceManager.GetString("MainStackBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MAIN STACK.
        /// </summary>
        public static string MainStackTitle {
            get {
                return ResourceManager.GetString("MainStackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esta é minha página profissional, onde busco contar um resumo da minha trajetória, elencar conhecimentos e expor projetos pessoais..
        /// </summary>
        public static string PresentationText {
            get {
                return ResourceManager.GetString("PresentationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a view projects.
        /// </summary>
        public static string ProjectsButton {
            get {
                return ResourceManager.GetString("ProjectsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a check out my personal projects.
        /// </summary>
        public static string SecondProjectsButton {
            get {
                return ResourceManager.GetString("SecondProjectsButton", resourceCulture);
            }
        }
    }
}
